- name: Setup environment on virtual machines
  hosts: aws
  become: true
  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: true

    - name: Install essential packages
      ansible.builtin.apt:
        name:
          - build-essential
          - curl
          - git
          - python3
          - python3-venv
          - python3-pip
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image from DockerHub
      docker_image:
        name: mustafa3li/project:latest
        source: pull

    - name: Run Docker container
      community.general.docker_container:
        name: taskmanger_container
        image: mustafa3li/project:latest
        state: started
        ports:
          - "8000:8000"